# references :
#
#       Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       .travis.yml for gcc-5 compiler support on Travis CI , https://gist.github.com/cotsog/3ce84675af0d74438d91
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages
#       Travis CI, Testing Your Project on Multiple Operating Systems, https://docs.travis-ci.com/user/multi-os/
#       Kalderimis & Nagy, Windows is Available (Early Release), Oct 10 2018, https://blog.travis-ci.com/2018-10-11-windows-early-release
#       Miniconda (Python 3) 4.5.11, Chocolatey Gallery, https://chocolatey.org/packages/miniconda3
#       The Windows Build Environment, https://docs.travis-ci.com/user/reference/windows/
#       QCGrids : a numerical integration library for quantum chemistry, https://github.com/theochem/qcgrids/
#       Caching Dependencies and Directories, https://docs.travis-ci.com/user/caching/
#       Caching is now enabled in Windows with rewritten caching utility, https://changelog.travis-ci.com/caching-is-now-enabled-in-windows-with-rewritten-caching-utility-76161
#       To which folder does Chocolatey download the packages before installing them?, https://stackoverflow.com/questions/38421395/to-which-folder-does-chocolatey-download-the-packages-before-installing-them

language: shell

env:
  - CONDA_PYTHON=3.6
  - CONDA_PYTHON=3.7
  - CONDA_PYTHON=nightly

os :
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os : windows
  fast_finish: true

before_cache:
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history $HOME/miniconda/envs/test-environment/conda-meta/history $HOME/miniconda/lib/python3.6/__pycache__ $HOME/miniconda/lib/python3.7/__pycache__/c/tools/miniconda3/locks /c/tools/miniconda3/pkgs /c/tools/miniconda3/var /c/tools/miniconda3/conda-meta/history /c/tools/miniconda3/envs/test-environment/conda-meta/history /c/tools/miniconda3/lib/python3.6/__pycache__ /c/tools/miniconda3/lib/python3.7/__pycache__

cache :
  directories:
    - $HOME/download
    - $HOME/miniconda
    - $HOME/AppData/Local/Temp/chocolatey

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  # Set conda path info
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      MINICONDA_PATH=$HOME/miniconda;
      MINICONDA_SUB_PATH=$MINICONDA_PATH/bin;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      MINICONDA_PATH=/c/tools/miniconda3;
      MINICONDA_SUB_PATH=$MINICONDA_PATH/Scripts;
    fi;
  - export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$PATH";
  # See if conda already available
  # Otherwise, see if miniconda installer available in cache
  # Still not, Obtain miniconda installer
  - if [[ -f `which conda` ]]; then
      echo "conda already available";
    else
      echo "need conda";
      echo $TRAVIS_OS_NAME;
      if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
        if [[ -f $HOME/download/miniconda.sh && $CONDA_PYTHON != "nightly" ]]; then
          echo "miniconda.sh for posix already available";
        else
          echo "downloading miniconda.sh for posix";
          mkdir -p $HOME/download;
          if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            echo "downloading miniconda.sh for linux";
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
          elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            echo "downloading miniconda.sh for osx";
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
          fi;
        fi;
      fi;
    fi;

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
    fi
  # To help debugging
  - echo $TRAVIS_OS_NAME
  - echo $CONDA_PYTHON
  # See of conda available
  # If necessary, install miniconda
  - if [[ -f `which conda` && "$CONDA_PYTHON"!="nightly" ]]; then
      echo "conda already available";
    else
      echo "still need conda";
      if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
        echo "install miniconda for posix";
        bash $HOME/download/miniconda.sh -b -p $MINICONDA_PATH;
      elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        echo "install miniconda for windows";
        choco install miniconda3;
      fi
    fi;
  # Forget all remembered locations
  - hash -r
  # Conda location
  - which conda
  # Conda setup options
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # To help debugging
  - echo $TRAVIS_OS_NAME
  - echo $CONDA_PYTHON
  # Useful for debugging any issues with conda
  - conda info -a
  # See if test-environment already available
  # As necessary, apply python module recipies
  - if [[ ! -d $MINICONDA_PATH/envs/test-environment ]]; then
      echo "create test-environment";
      conda env create -n test-environment python=$CONDA_PYTHON -f ./tests/environment.${CONDA_PYTHON}.yml;
    else
      echo "update test-environment";
      conda env update -n test-environment python=$CONDA_PYTHON -f ./tests/environment.${CONDA_PYTHON}.yml;
    fi;
  - source activate test-environment
  - conda list

# https://lord.io/blog/2014/travis-multiple-subdirs/
script: cd tests && py.test
notifications:
    email:
        - kangwon.lee.edu@gmail.com
